### ISSUE TITLE
MISW/PortalをOSSに！

### ISSUE THREAD

**Issue by tsuzu** [MISW/Portal#178]
特にプライベートにする必要がないものは積極的にオープンにしていきたい

- [x] dev.env内のOIDC_CLIENT_SECRETを置き換え
- [x] dev.env内のSMTP_PASSWORDを置き換え
- [x] [email_test.go](https://github.com/MISW/Portal/blob/f1c78ab40c6ef877ba9de32c09e8184dca7c574f/backend/internal/email/email_test.go#L20) のパスワードを置き換え

**Comment by cs3238-tsuzu** [comment]
READMEを整えていきたい
