### ISSUE TITLE
領収書付きの支払い完了メールが必要。

### ISSUE THREAD

**Issue by CaffeeLake** [MISW/portal#850]
現在、入会金を支払後の、Slack招待メール以外は、支払い完了時にメールが届かない。
支払いが完了したかの確認は、手動でPortalにアクセスしなければならない。
なので、支払いが完了したかの通知と、支払ったことを示す領収書が必要。

- [ ] 支払い完了メール
- [ ] 領収書

**Comment by SnakeSneakS** [comment]
上のプルリクで支払い完了メール送信はとりあえずできたが、メール送信に失敗した時のための対策や、支払い金額の表示はできていない。
