### ISSUE TITLE
ログアウトをすると、再度ログインされる。

### ISSUE THREAD

**Issue by CaffeeLake** [MISW/portal#916]

**Comment by SnakeSneakS** [comment]
- 方法1: ログインボタン的なのを間に挟む
- 方法2: ログアウトした時に自動ログインしないどこかのページに飛ばす(ヘビの好み)

**Comment by SnakeSneakS** [comment]
ソースコード読みながら、みすポータルではログアウト(cookieに保存しているtokenの無効化)はしてるけど、auth0の方ではしていないやんっとなったので、logoutURLを出してログアウトするようにしてみます　b

**Comment by SnakeSneakS** [comment]
上のブランチのマージによって終了
