### ISSUE TITLE
slackからdiscordへの移行

### ISSUE THREAD

**Issue by SnakeSneakS** [MISW/portal#918]
slackの仕様変更(90日以前のメッセージ閲覧不可)を受けてメインの連絡をDiscordで行うようになったため、それを受けてみすポータルでもslackからDiscordへ移行していきたい

**Comment by CaffeeLake** [comment]
ソーシャルログインをDiscordに移行した場合、Kibelaやみすクラウドでログインする際に、今のアカウントではなく、別のアカウントとして認識されるので、その辺ってどう対応するつもりですか?

**Comment by SnakeSneakS** [comment]
(kibelaに関してはメールアドレス準拠なのでdiscordの方のメアドをslackと合わせるようにした方がいいってアナウンスするべきだと考えてるっていうのはそれはそれとして、)
別のアカウントになるのは移行する以上致し方ないかなって考えてますね〜

あとは、slackでもdiscordでもどちらでもログインできるようにして、緩やかな移行期間をとるっていうのは嬉しいと思うけれど、それはそれで実装複雑になりそうなのでう〜ん...

**Comment by SnakeSneakS** [comment]
→ slackとdiscordどっちもできるようにするの、auth0がやってくれて実はそんなに難しくないのでは！？って気持ちになったなう

**Comment by SnakeSneakS** [comment]
discordとslack両方使えるということで、close
